apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/compte_github/application-deployment.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-${SSPCLOUD_USERNAME}
  syncPolicy:
    automated:
      selfHeal: true
